

default_platform(:android)

platform :android do
  desc "lane for firebase distribution android"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:243082444103:android:6a4a7d23d36dc0b6e1a062",
    firebase_cli_token: ENV["Firebase_CLI_Token"],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "elbahnasawy114@gmail.com",
    release_notes: "first fastlane release to firebase distribution"
  )
  end

end
